# Generated by Django 4.1.6 on 2023-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Pessoa')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
            ],
        ),
    ]
