# Generated by Django 4.1.6 on 2023-04-02 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=' Data da Receita '),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(verbose_name='Igredientes'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(verbose_name='Modo de Preparo'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=100, verbose_name='Nome da Receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(max_length=100, verbose_name='Remdimento'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(verbose_name='Tempo de Preparo'),
        ),
    ]
